<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">


        </div>
        <div class="span9">
    <!-- Modal
    ================================================== -->
            <section id="modals">
            <div class="page-header">
                &nbsp;
            </div>

            <div>
                <phx:Dummy id="dummy" />
            </div>
                <table>
                <tr>
                    <td width="50%">
                        <div id="dataGrid" >
                            <phx:Grid id="grid0" anchor="#grid" pageCount="20" />
                        </div>
                    </td>
                    <td width="50%">
                        <div id="vikipedia">
                            
                        </div>
                    </td>
                </tr>
                </table>
            </div>
                
            <div id="token">

            </div>


            </section>

        </div>
    </div>
</div>
