#!/bin/bash
echo > /Users/david/Sites/CodePhoenixOrg/SDK/php/LAdmin/web/php_error_log
echo > /Users/david/Sites/CodePhoenixOrg/SDK/php/LAdmin/logs/debug.log
find /Users/david/Sites/CodePhoenixOrg/SDK/php/LAdmin/runtime -type f -exec rm -f {} \; 
find /Users/david/Sites/CodePhoenixOrg/SDK/php/LAdmin/web/js/runtime -type f -exec rm -f {} \; 
echo "All logs and temporary files cleared at "$(date) 
exit 0

