
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="javascript:logout()">LAdmin</a>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
                <li><a id="home">Accueil</a></li>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-header">Outils</li>
                    <li><a id="passwd">Générateur de mot de passe</a></li>
                    <li><a id="sample">Exemple de multi-accordéon</a></li>
                  </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-right">
              <div class="form-group">
                <input placeholder="Email" class="form-control" type="text" readonly="readonly">
              </div>
              <button id="disconnect"  type="submit" class="btn btn-danger">Déconnexion</button>
            </form>
          </div>
        </div>
    </div>
    

<header class="jumbotron subhead">

  <div class="container" >

    <div class="row" id="core" >

    </div>

  </div>

    <footer class="footer">
      <div class="container">
        <p><a href="#" id="logout" target="_new" >Déconnexion</a></p>
      </div>
    </footer>


   
